name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-and-release:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.10.0
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: List installed packages (debug)
        run: pnpm list
        
      - name: Verify electron-builder installation
        run: pnpm electron-builder --help || echo "electron-builder not found"
        
      - name: Build application (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Building for Linux..."
          pnpm run build:linux
        env:
          DEBUG: electron-builder
          
      - name: Build application (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "Building for Windows..."
          pnpm run build:win
        env:
          DEBUG: electron-builder
          
      - name: Build application (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          echo "Building for macOS..."
          pnpm run build:mac
        env:
          DEBUG: electron-builder
          
      - name: List build output (debug)
        run: |
          echo "Listing dist directory:"
          ls -la dist/ || echo "dist directory not found"
          find . -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" 2>/dev/null || echo "No build artifacts found"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/**/*
            !dist/**/node_modules/**
          retention-days: 30
          if-no-files-found: warn
          
  release:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event.pull_request.merged == true)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          
      - name: List downloaded artifacts (debug)
        run: |
          echo "Downloaded artifacts:"
          find ./artifacts -type f -name "*" | head -20
          
      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}-${{ github.run_number }}
          release_name: Release v${{ steps.get_version.outputs.VERSION }}-${{ github.run_number }}
          body: |
            Auto-generated release for JourneyBookAI
            
            Changes in this release:
            - Latest changes from main branch
            
            ## Downloads
            - Windows: `.exe` installer
            - macOS: `.dmg` installer  
            - Linux: `.AppImage` or `.deb` package
          draft: false
          prerelease: false
          
      - name: Upload Release Assets
        run: |
          for file in $(find ./artifacts -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.zip" \)); do
            if [ -f "$file" ]; then
              echo "Uploading $file"
              gh release upload v${{ steps.get_version.outputs.VERSION }}-${{ github.run_number }} "$file" || echo "Failed to upload $file"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}